liip_monitor:
    # enabling the controller requires that `assets` are enabled in the framework bundle
    enable_controller: true
    checks:
        php_extensions: [pdo]
        doctrine_dbal: default
        php_version:
            "7.4": ">="
